apiVersion: v1
kind: Service
metadata:
  name: {{ template "bitcoind.fullname" . }}
  labels:
    app: {{ template "bitcoind.name" . }}
    chart: {{ template "bitcoind.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  type: LoadBalancer
  ports:
    - name: rpc
      port: {{ .Values.service.rpcPort }}
      targetPort: {{ .Values.service.rpcPort }}
    - name: p2p
      port: {{ .Values.service.p2pPort }}
      targetPort: {{ .Values.service.p2pPort }}
    - name: testnet
      port: {{ .Values.service.testnetPort }}
      targetPort: {{ .Values.service.testnetPort }}
    - name: testnet-p2p
      port: {{ .Values.service.testnetP2pPort }}
      targetPort: {{ .Values.service.testnetP2pPort }}
    - name: zmqblock
      port: {{ .Values.service.zmqBlockPort }}
      targetPort: {{ .Values.service.zmqBlockPort }}
    - name: zmqtx
      port: {{ .Values.service.zmqTxPort }}
      targetPort: {{ .Values.service.zmqTxPort }}
  selector:
    app: {{ template "bitcoind.name" . }}
    release: {{ .Release.Name }}
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx

